# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5ac61992bf2273798f81e5f51a6d26a7cd494009c8fffb1d2d1d7987577acf9f433dc4fa011248bdcf9149e6fcf873ce3205b477f00a10cd66be81ac940feda

test:
  secret_key_base: 0e0115892aa701b21eb3b1fca4546f93a082bc2cc0b72ffe6536f4b70336b5020e60f3a228fcd8e29c89f0b931160dcc1a93fc8029612f174d790c5015515f58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
